// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGT-EyB8Er_Q8Gm7e3Jwq3hQCJrAaGLC8',
    appId: '1:250027172547:web:118ec6e87c16fa44397876',
    messagingSenderId: '250027172547',
    projectId: 'flutter-ecommerce-mvc-42135',
    authDomain: 'flutter-ecommerce-mvc-42135.firebaseapp.com',
    storageBucket: 'flutter-ecommerce-mvc-42135.appspot.com',
    measurementId: 'G-C72JRH3LMP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-otWgsvGq93FIxIEGWht_18Tw7bQ9u6Y',
    appId: '1:250027172547:android:86843f55b631dd82397876',
    messagingSenderId: '250027172547',
    projectId: 'flutter-ecommerce-mvc-42135',
    storageBucket: 'flutter-ecommerce-mvc-42135.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2QKuZwYv0O5ZnHJSFAF_-ZK3Hs9wZzxg',
    appId: '1:250027172547:ios:d9eab5c09cd5b27f397876',
    messagingSenderId: '250027172547',
    projectId: 'flutter-ecommerce-mvc-42135',
    storageBucket: 'flutter-ecommerce-mvc-42135.appspot.com',
    iosBundleId: 'com.example.flutterEcommerceMvc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2QKuZwYv0O5ZnHJSFAF_-ZK3Hs9wZzxg',
    appId: '1:250027172547:ios:75c38e2ff500e885397876',
    messagingSenderId: '250027172547',
    projectId: 'flutter-ecommerce-mvc-42135',
    storageBucket: 'flutter-ecommerce-mvc-42135.appspot.com',
    iosBundleId: 'com.example.flutterEcommerceMvc.RunnerTests',
  );
}
